# Generated by Django 3.2.5 on 2021-10-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.TextField(max_length=20, unique=True)),
                ('Last_Name', models.TextField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
