# Generated by Django 3.2.5 on 2021-10-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Two', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='First_Name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='Last_Name',
            field=models.TextField(max_length=20),
        ),
    ]
